namespace: wackopicko
working_dir: .
language: ES
strict: false
output:
  file_path: results-sast.sarif
  format: SARIF
sast:
  include:
    - website/
  exclude:
    - glob(website/css/blueprint/**)
    - glob(website/upload/**)
