namespace: wackopicko
working_dir: .
language: ES
strict: false
output:
  file_path: results-sca.sarif
  format: SARIF
sca:
  include:
    - .
  exclude:
    - glob(website/css/blueprint/**)
    - glob(website/upload/**)
