namespace: wackopicko
working_dir: .
language: ES
strict: true
output:
  file_path: results-sast.csv
  format: CSV
sast:
  include:
    - website/
  exclude:
    - glob(website/css/blueprint/**)
    - glob(website/upload/**)
