namespace: wackopicko
working_dir: .
language: ES
strict: true
strictness_threshold: high
output:
  file_path: results-sca.csv
  format: CSV
sca:
  include:
    - .
  exclude:
    - glob(website/css/blueprint/**)
    - glob(website/upload/**)
