name: SCA (Paso 2)

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.2.0
        with:
          scan_config_path: .github/paso2/sca-config.yaml
